"""
This type stub file was generated by pyright.
"""

import logging
from .cache import Cache, cache
from .backends import DeserializationException, SerializationException

"""Package that automatically caches and dispatch serialization and deserialization to the correct functions depending on the extension."""
__all__ = ["Cache", "cache", "SerializationException", "DeserializationException"]
