# pyright: reportExplicitAny=none, reportAny=none
"""This type stub file was generated by pyright."""

from ast import TypeVar
from collections.abc import Sequence
from typing import Any, Callable, ParamSpec

log_levels: dict[str, int] = ...

def cache(function: Callable[..., Any]) -> Callable[..., Any]: ...

_P = ParamSpec("_P")
_R = TypeVar("_R")

class Cache:
    is_backup_enabled: bool = True
    args_to_ignore: list[str]
    optional_path_keys: list[str]

    def __init__(
        self,
        cache_path: str | tuple[str] | list[str] | dict[str, str] = ...,
        args_to_ignore: Sequence[str] = (),
        cache_dir: str | None = None,
        validity_duration: int | str = -1,
        use_source_code: bool = True,
        use_approximated_hash: bool = False,
        log_level: str = "critical",
        log_format: str = ...,
        backup_path: str | None = None,
        backup: bool = True,
        optional_path_keys: list[str] | None = None,
        dump_kwargs: dict[str, Any] = ...,
        load_kwargs: dict[str, Any] = ...,
        enable_cache_arg_name: str | None = None,
        capture_enable_cache_arg_name: bool = True,
    ) -> None: ...
    @staticmethod
    def store(obj: object, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> object: ...
    @staticmethod
    def compute_path(function: Callable[..., Any], *args: Any, **kwargs: Any) -> str: ...
    def decorate(self, function: Callable[_P, Any]) -> Callable[_P, Any]: ...
    def __call__(self, function: Callable[..., Any]) -> Callable[..., Any]: ...
