# pyright: reportExplicitAny=false, reportAny=false
"""This type stub file was generated by pyright."""

from typing import Any

from amazonorders.conf import AmazonOrdersConfig
from amazonorders.forms import AuthForm
from amazonorders.util import AmazonSessionResponse
from requests import Response
from requests.sessions import Session

class IODefault:
    def echo(self, msg: str, **kwargs: Any) -> None: ...
    def prompt(self, msg: str, type: Any | None = None, **kwargs: Any) -> str:
        """Prompt to the console for user input.

        :param msg: The data to use as the input prompt.
        :param type: Unused by the default implementation.
        :param kwargs: Unused by the default implementation.
        :return: The user input result.
        """
        ...

class AmazonSession:
    session: Session
    is_authenticated: bool = False

    def __init__(
        self,
        username: str | None = None,
        password: str | None = None,
        debug: bool = False,
        io: IODefault = ...,
        config: AmazonOrdersConfig | None = None,
        auth_forms: list[AuthForm] | None = ...,
        otp_secret_key: str | None = ...,
    ) -> None: ...
    def request(
        self, method: str, url: str, persist_cookies: bool = ..., **kwargs: Any
    ) -> AmazonSessionResponse: ...
    def get(self, url: str, **kwargs: Any) -> AmazonSessionResponse: ...
    def post(self, url: str, **kwargs: Any) -> AmazonSessionResponse: ...
    def auth_cookies_stored(self) -> bool: ...
    def login(self) -> None: ...
    def logout(self) -> None: ...
    def build_response_error(self, response: Response) -> str: ...
    def check_response(
        self, amazon_session_response: AmazonSessionResponse, meta: dict[str, Any] | None = None
    ) -> None: ...
