"""
This type stub file was generated by pyright.
"""

class BackendTemplate:
    """To serialize and de-serialize data we need double dynamic dispatching, 
    thus this is the template for all the implementations.
    
    The backends must be implemented in such a way that:
    backend = Backend(load_kwargs, dump_kwargs)
    backend.load(backend.dump(object, "./test"), "./test") == object
    """
    SUPPORTED_EXTENSIONS = ...
    def __init__(self, load_kwargs, dump_kwargs) -> None:
        """The init must always handle kwargs since """
        ...
    
    @staticmethod
    def support_path(path: str) -> bool:
        """Returns if the current backend MIGHT serialize and deserialize the given path.
        This is a might because the given object might not be serializable, but we
        support the extension."""
        ...
    
    @staticmethod
    def can_serialize(obj_to_serialize: object, path: str) -> bool:
        """Must return if the current backend can handle the type of data."""
        ...
    
    def dump(self, obj_to_serialize: object, path: str) -> dict:
        """Serialize and save the object at the given path.
        If this backend needs extra informations to de-serialize data, it can 
        return them as a dictionary which will be serialized as a json."""
        ...
    
    @staticmethod
    def can_deserialize(metadata: dict, path: str) -> bool:
        """Must return if the current backend can handle the type of data."""
        ...
    
    def load(self, metadata: dict, path: str) -> object:
        """Load the method at the given path. If the medod need extra
        informations it can read them form the metadata dictionary which is
        the return value of the dump method."""
        ...
    


