"""
This type stub file was generated by pyright.
"""

from typing import Set

class Backend:
    def __init__(self, load_kwargs, dump_kwargs) -> None:
        ...
    
    def support_path(self, path: str) -> bool:
        """If exists at least one backend that can handle the current path."""
        ...
    
    def get_supported_extensions(self) -> Set[str]:
        """Get the supported extensions."""
        ...
    
    def dump(self, obj_to_serialize: object, path: str) -> dict:
        """Serialize and save the object at the given path.
        If this backend needs extra informations to de-serialize data, it can 
        return them as a dictionary which will be serialized as a json."
        If the function returns None or does not return, an empty dictionary
        will be used as metadata."""
        ...
    
    def load(self, metadata: dict, path: str) -> object:
        """Load the method at the given path. If the medod need extra
        informations it can """
        ...
    


