"""
This type stub file was generated by pyright.
"""

class SerializationException(Exception):
    def __init__(self, error_message, path, result, backup_path=...) -> None:
        ...
    


class DeserializationException(Exception):
    def __init__(self, error_message, path, backup_path=...) -> None:
        ...
    


