"""
This type stub file was generated by pyright.
"""

from .backend_template import BackendTemplate

"""Backend for Keras models."""
def create_tar(src_dir, tar_file, extension): # -> None:
    ...

def get_extension(path): # -> Literal['', 'gz', 'bz2', 'xz']:
    ...

class KerasModelBackend(BackendTemplate):
    """Backend for Keras models."""
    SUPPORTED_EXTENSIONS = ...
    @staticmethod
    def support_path(path: str) -> bool:
        ...
    
    @staticmethod
    def can_deserialize(metadata: dict, path: str) -> bool:
        ...
    
    @staticmethod
    def can_serialize(obj_to_serialize: object, path: str) -> bool:
        ...
    
    def dump(self, obj_to_serialize: Model, path: str) -> dict:
        ...
    
    def load(self, metadata: dict, path: str) -> object:
        ...
    


