"""
This type stub file was generated by pyright.
"""

import pandas as pd
from .backend_template import BackendTemplate

def is_consistent(series: pd.Series) -> bool:
    """Check that all the values in the series are of the same type."""
    ...

def get_vector_dtype(series: pd.Series) -> str:
    """Get which type to use to serialize the type of the series"""
    ...

common_message = ...
class PandasCsvBackend(BackendTemplate):
    SUPPORTED_EXTENSIONS = ...
    def __init__(self, load_kwargs, dump_kwargs) -> None:
        ...
    
    @staticmethod
    def support_path(path: str) -> bool:
        ...
    
    @staticmethod
    def can_deserialize(metadata: dict, path: str) -> bool:
        ...
    
    @staticmethod
    def can_serialize(obj_to_serialize: object, path: str) -> bool:
        ...
    
    def dump(self, obj_to_serialize: pd.DataFrame, path: str) -> dict:
        ...
    
    def load(self, metadata: dict, path: str) -> object:
        ...
    


