"""
This type stub file was generated by pyright.
"""

import pandas as pd
from .backend_template import BackendTemplate

def is_numeric_dataframe(df: pd.DataFrame) -> bool:
    """Check if all the columns have numerical data types."""
    ...

class PandasEmbeddingBackend(BackendTemplate):
    """This format is optimzied to compress datafarmes that contains ONLY numerical values.
        For .gz and .bz2 you can use the load_kwarg `compresslevel` to set the 
        compression level (default 9). For .xz you can use the load_kwarg preset
        to set the compression level."""
    SUPPORTED_EXTENSIONS = ...
    def __init__(self, load_kwargs, dump_kwargs) -> None:
        ...
    
    @staticmethod
    def support_path(path: str) -> bool:
        ...
    
    @staticmethod
    def can_deserialize(metadata: dict, path: str) -> bool:
        ...
    
    @staticmethod
    def can_serialize(obj_to_serialize: object, path: str) -> bool:
        ...
    
    def dump(self, obj_to_serialize: pd.DataFrame, path: str) -> dict:
        ...
    
    def load(self, metadata: dict, path: str) -> object:
        ...
    


