"""
This type stub file was generated by pyright.
"""

from .backend_template import BackendTemplate

class PickleBackend(BackendTemplate):
    SUPPORTED_EXTENSIONS = ...
    def __init__(self, load_kwargs, dump_kwargs) -> None:
        ...
    
    @staticmethod
    def support_path(path: str) -> bool:
        ...
    
    @staticmethod
    def can_serialize(obj_to_serialize: object, path: str) -> bool:
        ...
    
    @staticmethod
    def can_deserialize(metadata: dict, path: str) -> bool:
        ...
    
    def dump(self, obj_to_serialize: object, path: str) -> dict:
        ...
    
    def load(self, metadata: dict, path: str) -> object:
        ...
    


