"""
This type stub file was generated by pyright.
"""

from .parse_time import parse_time
from .get_params import get_params
from .random_string import random_string
from .get_format_groups import get_format_groups, get_next_format_group

def get_function_name(function) -> str:
    ...

__all__ = ["parse_time", "get_params", "random_string", "get_format_groups", "get_next_format_group", "get_function_name"]
