"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Tuple

class MatchGroup:
    def __init__(self, str_match: str, start: int, end: int) -> None:
        ...
    


def get_format_groups(path_fmt: str) -> List[MatchGroup]:
    """Given a format string extract the name of the values to substitute."""
    ...

def get_next_format_group(path_fmt: str) -> Tuple[Optional[MatchGroup], str]:
    """Given a format string extract the first Match (None if there are none), 
    and return the remainder of the format string (the part not yet parsed)."""
    ...

