"""This type stub file was generated by pyright."""

import datetime as dt
from typing import TypeVar

from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.item import Item
from amazonorders.entity.parsable import Parsable
from amazonorders.entity.recipient import Recipient
from amazonorders.entity.shipment import Shipment
from bs4 import Tag

OrderEntity = TypeVar("OrderEntity", bound="Order")

class Order(Parsable):
    full_details: bool
    index: int | None
    shipments: list[Shipment]
    items: list[Item]
    order_number: str
    order_details_link: str | None
    grand_total: float
    order_placed_date: dt.date
    recipient: Recipient
    payment_method: str | None
    payment_method_last_4: int | None
    subtotal: float | None
    shipping_total: float | None
    free_shipping: bool | None
    promotion_applied: float | None
    coupon_savings: float | None
    subscription_discount: float | None
    total_before_tax: float | None
    estimated_tax: float | None
    refund_total: float | None

    def __init__(
        self,
        parsed: Tag,
        config: AmazonOrdersConfig,
        full_details: bool = ...,
        clone: Order | None = ...,
        index: int | None = ...,
    ) -> None: ...
