"""This type stub file was generated by pyright."""

from datetime import date

from amazonorders.conf import AmazonOrdersConfig
from amazonorders.entity.parsable import Parsable
from bs4 import Tag

class Transaction(Parsable):
    completed_date: date
    payment_method: str
    grand_total: float
    is_refund: bool
    order_number: str
    order_details_link: str
    seller: str

    def __init__(self, parsed: Tag, config: AmazonOrdersConfig, completed_date: date) -> None: ...
